language: android
sudo: false
android:
  components:
    - android-28
    - build-tools-28.0.3
    - android-22
    - sys-img-armeabi-v7a-android-22

script:
  # other script steps might be done before running the actual analysis
  - echo "starting script"
  - ./gradlew clean build
