package de.gardeningplanner.model;

import org.apache.commons.collections4.map.MultiKeyMap;

import de.gardeningplanner.model.crops.Aubergine;
import de.gardeningplanner.model.crops.Beetroot;
import de.gardeningplanner.model.crops.BushBean;
import de.gardeningplanner.model.crops.Cabbage;
import de.gardeningplanner.model.crops.Carrot;
import de.gardeningplanner.model.crops.Celery;
import de.gardeningplanner.model.crops.Chard;
import de.gardeningplanner.model.crops.ChineseCabbage;
import de.gardeningplanner.model.crops.Crop;
import de.gardeningplanner.model.crops.CropTolerance;
import de.gardeningplanner.model.crops.Cucumber;
import de.gardeningplanner.model.crops.Endive;
import de.gardeningplanner.model.crops.Fennel;
import de.gardeningplanner.model.crops.Garlic;
import de.gardeningplanner.model.crops.Horseradish;
import de.gardeningplanner.model.crops.Kohlrabi;
import de.gardeningplanner.model.crops.LambsLettuce;
import de.gardeningplanner.model.crops.Leek;
import de.gardeningplanner.model.crops.Lettuce;
import de.gardeningplanner.model.crops.Onion;
import de.gardeningplanner.model.crops.Pea;
import de.gardeningplanner.model.crops.Potato;
import de.gardeningplanner.model.crops.Radish;
import de.gardeningplanner.model.crops.Rhubarb;
import de.gardeningplanner.model.crops.RunnerBeans;
import de.gardeningplanner.model.crops.Spinach;
import de.gardeningplanner.model.crops.Strawberry;
import de.gardeningplanner.model.crops.Zucchini;

public class MixedCultureEvaluator {

    private MultiKeyMap<String, CropTolerance> toleranceMap;

    public MixedCultureEvaluator(){
        toleranceMap = new MultiKeyMap<>();
        populateToleranceMap();
    }

    public CropTolerance getTolerance(Crop crop1, Crop crop2){
        /*if(toleranceMap.containsKey(crop1.getName(),crop2.getName())){
        */    return toleranceMap.get(crop1.getName(), crop2.getName());
        /*}else{
            return CropTolerance.NEUTRAL;
        }*/
    }

    private void populateToleranceMap() {
        toleranceMap.put("Aubergine", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "Beetroot", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "BushBean", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "Cabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Aubergine", "Carrot", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Aubergine", "Celery", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "Chard", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "ChineseCabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "Cucumber", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "Fennel", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "Garlic", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "Kohlrabi", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "LambsLettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "Leek", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "Lettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Aubergine", "Onion", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "Pea", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "Potato", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "Radish", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "RunnerBeans", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "Spinach", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Aubergine", "Strawberry", CropTolerance.NEUTRAL);
        toleranceMap.put("Aubergine", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("Beetroot", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("Beetroot", "Beetroot", CropTolerance.NEUTRAL);
        toleranceMap.put("Beetroot", "BushBean", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Beetroot", "Cabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Beetroot", "Carrot", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Beetroot", "Celery", CropTolerance.NEUTRAL);
        toleranceMap.put("Beetroot", "Chard", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Beetroot", "ChineseCabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Beetroot", "Cucumber", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Beetroot", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("Beetroot", "Fennel", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Beetroot", "Garlic", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Beetroot", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Beetroot", "Kohlrabi", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Beetroot", "LambsLettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Beetroot", "Leek", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Beetroot", "Lettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Beetroot", "Onion", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Beetroot", "Pea", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Beetroot", "Potato", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Beetroot", "Radish", CropTolerance.NEUTRAL);
        toleranceMap.put("Beetroot", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("Beetroot", "RunnerBeans", CropTolerance.NEUTRAL);
        toleranceMap.put("Beetroot", "Spinach", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Beetroot", "Strawberry", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Beetroot", "Zucchini", CropTolerance.SUPPORTIVE);

        toleranceMap.put("BushBean", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("BushBean", "Beetroot", CropTolerance.SUPPORTIVE);
        toleranceMap.put("BushBean", "BushBean", CropTolerance.NEUTRAL);
        toleranceMap.put("BushBean", "Cabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("BushBean", "Carrot", CropTolerance.NEUTRAL);
        toleranceMap.put("BushBean", "Celery", CropTolerance.SUPPORTIVE);
        toleranceMap.put("BushBean", "Chard", CropTolerance.SUPPORTIVE);
        toleranceMap.put("BushBean", "ChineseCabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("BushBean", "Cucumber", CropTolerance.SUPPORTIVE);
        toleranceMap.put("BushBean", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("BushBean", "Fennel", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("BushBean", "Garlic", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("BushBean", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("BushBean", "Kohlrabi", CropTolerance.SUPPORTIVE);
        toleranceMap.put("BushBean", "LambsLettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("BushBean", "Leek", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("BushBean", "Lettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("BushBean", "Onion", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("BushBean", "Pea", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("BushBean", "Potato", CropTolerance.SUPPORTIVE);
        toleranceMap.put("BushBean", "Radish", CropTolerance.SUPPORTIVE);
        toleranceMap.put("BushBean", "Rhubarb", CropTolerance.SUPPORTIVE);
        toleranceMap.put("BushBean", "RunnerBeans", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("BushBean", "Spinach", CropTolerance.SUPPORTIVE);
        toleranceMap.put("BushBean", "Strawberry", CropTolerance.SUPPORTIVE);
        toleranceMap.put("BushBean", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("Cabbage", "Aubergine", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cabbage", "Beetroot", CropTolerance.NEUTRAL);
        toleranceMap.put("Cabbage", "BushBean", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cabbage", "Cabbage", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Cabbage", "Carrot", CropTolerance.NEUTRAL);
        toleranceMap.put("Cabbage", "Celery", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cabbage", "Chard", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cabbage", "ChineseCabbage", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Cabbage", "Cucumber", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cabbage", "Endive", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cabbage", "Fennel", CropTolerance.NEUTRAL);
        toleranceMap.put("Cabbage", "Garlic", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Cabbage", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Cabbage", "Kohlrabi", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Cabbage", "LambsLettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cabbage", "Leek", CropTolerance.NEUTRAL);
        toleranceMap.put("Cabbage", "Lettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cabbage", "Onion", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Cabbage", "Pea", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cabbage", "Potato", CropTolerance.NEUTRAL);
        toleranceMap.put("Cabbage", "Radish", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cabbage", "Rhubarb", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cabbage", "RunnerBeans", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cabbage", "Spinach", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cabbage", "Strawberry", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cabbage", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("Carrot", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("Carrot", "Beetroot", CropTolerance.NEUTRAL);
        toleranceMap.put("Carrot", "BushBean", CropTolerance.NEUTRAL);
        toleranceMap.put("Carrot", "Cabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Carrot", "Carrot", CropTolerance.NEUTRAL);
        toleranceMap.put("Carrot", "Celery", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Carrot", "Chard", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Carrot", "ChineseCabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Carrot", "Cucumber", CropTolerance.NEUTRAL);
        toleranceMap.put("Carrot", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("Carrot", "Fennel", CropTolerance.NEUTRAL);
        toleranceMap.put("Carrot", "Garlic", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Carrot", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Carrot", "Kohlrabi", CropTolerance.NEUTRAL);
        toleranceMap.put("Carrot", "LambsLettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Carrot", "Leek", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Carrot", "Lettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Carrot", "Onion", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Carrot", "Pea", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Carrot", "Potato", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Carrot", "Radish", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Carrot", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("Carrot", "RunnerBeans", CropTolerance.NEUTRAL);
        toleranceMap.put("Carrot", "Spinach", CropTolerance.NEUTRAL);
        toleranceMap.put("Carrot", "Strawberry", CropTolerance.NEUTRAL);
        toleranceMap.put("Carrot", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("Celery", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("Celery", "Beetroot", CropTolerance.NEUTRAL);
        toleranceMap.put("Celery", "BushBean", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Celery", "Cabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Celery", "Carrot", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Celery", "Celery", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Celery", "Chard", CropTolerance.NEUTRAL);
        toleranceMap.put("Celery", "ChineseCabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Celery", "Cucumber", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Celery", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("Celery", "Fennel", CropTolerance.NEUTRAL);
        toleranceMap.put("Celery", "Garlic", CropTolerance.NEUTRAL);
        toleranceMap.put("Celery", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Celery", "Kohlrabi", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Celery", "LambsLettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Celery", "Leek", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Celery", "Lettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Celery", "Onion", CropTolerance.NEUTRAL);
        toleranceMap.put("Celery", "Pea", CropTolerance.NEUTRAL);
        toleranceMap.put("Celery", "Potato", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Celery", "Radish", CropTolerance.NEUTRAL);
        toleranceMap.put("Celery", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("Celery", "RunnerBeans", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Celery", "Spinach", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Celery", "Strawberry", CropTolerance.NEUTRAL);
        toleranceMap.put("Celery", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("Chard", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "Beetroot", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Chard", "BushBean", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Chard", "Cabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "Carrot", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Chard", "Celery", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "Chard", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "ChineseCabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "Cucumber", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "Fennel", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "Garlic", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "Kohlrabi", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "LambsLettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "Leek", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "Lettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "Onion", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "Pea", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "Potato", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "Radish", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Chard", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "RunnerBeans", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "Spinach", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Chard", "Strawberry", CropTolerance.NEUTRAL);
        toleranceMap.put("Chard", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("ChineseCabbage", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("ChineseCabbage", "Beetroot", CropTolerance.NEUTRAL);
        toleranceMap.put("ChineseCabbage", "BushBean", CropTolerance.SUPPORTIVE);
        toleranceMap.put("ChineseCabbage", "Cabbage", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("ChineseCabbage", "Carrot", CropTolerance.SUPPORTIVE);
        toleranceMap.put("ChineseCabbage", "Celery", CropTolerance.NEUTRAL);
        toleranceMap.put("ChineseCabbage", "Chard", CropTolerance.NEUTRAL);
        toleranceMap.put("ChineseCabbage", "ChineseCabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("ChineseCabbage", "Cucumber", CropTolerance.NEUTRAL);
        toleranceMap.put("ChineseCabbage", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("ChineseCabbage", "Fennel", CropTolerance.NEUTRAL);
        toleranceMap.put("ChineseCabbage", "Garlic", CropTolerance.NEUTRAL);
        toleranceMap.put("ChineseCabbage", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("ChineseCabbage", "Kohlrabi", CropTolerance.NEUTRAL);
        toleranceMap.put("ChineseCabbage", "LambsLettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("ChineseCabbage", "Leek", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("ChineseCabbage", "Lettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("ChineseCabbage", "Onion", CropTolerance.NEUTRAL);
        toleranceMap.put("ChineseCabbage", "Pea", CropTolerance.SUPPORTIVE);
        toleranceMap.put("ChineseCabbage", "Potato", CropTolerance.NEUTRAL);
        toleranceMap.put("ChineseCabbage", "Radish", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("ChineseCabbage", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("ChineseCabbage", "RunnerBeans", CropTolerance.NEUTRAL);
        toleranceMap.put("ChineseCabbage", "Spinach", CropTolerance.SUPPORTIVE);
        toleranceMap.put("ChineseCabbage", "Strawberry", CropTolerance.NEUTRAL);
        toleranceMap.put("ChineseCabbage", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("Cucumber", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("Cucumber", "Beetroot", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cucumber", "BushBean", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cucumber", "Cabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cucumber", "Carrot", CropTolerance.NEUTRAL);
        toleranceMap.put("Cucumber", "Celery", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cucumber", "Chard", CropTolerance.NEUTRAL);
        toleranceMap.put("Cucumber", "ChineseCabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Cucumber", "Cucumber", CropTolerance.NEUTRAL);
        toleranceMap.put("Cucumber", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("Cucumber", "Fennel", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cucumber", "Garlic", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cucumber", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Cucumber", "Kohlrabi", CropTolerance.NEUTRAL);
        toleranceMap.put("Cucumber", "LambsLettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Cucumber", "Leek", CropTolerance.NEUTRAL);
        toleranceMap.put("Cucumber", "Lettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Cucumber", "Onion", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cucumber", "Pea", CropTolerance.NEUTRAL);
        toleranceMap.put("Cucumber", "Potato", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Cucumber", "Radish", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Cucumber", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("Cucumber", "RunnerBeans", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Cucumber", "Spinach", CropTolerance.NEUTRAL);
        toleranceMap.put("Cucumber", "Strawberry", CropTolerance.NEUTRAL);
        toleranceMap.put("Cucumber", "Zucchini", CropTolerance.OBSTRUCTIVE);

        toleranceMap.put("Endive", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "Beetroot", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "BushBean", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "Cabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Endive", "Carrot", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "Celery", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "Chard", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "ChineseCabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "Cucumber", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "Fennel", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Endive", "Garlic", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "Kohlrabi", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "LambsLettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "Leek", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Endive", "Lettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "Onion", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "Pea", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "Potato", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "Radish", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "RunnerBeans", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Endive", "Spinach", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "Strawberry", CropTolerance.NEUTRAL);
        toleranceMap.put("Endive", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("Fennel", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("Fennel", "Beetroot", CropTolerance.NEUTRAL);
        toleranceMap.put("Fennel", "BushBean", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Fennel", "Cabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Fennel", "Carrot", CropTolerance.NEUTRAL);
        toleranceMap.put("Fennel", "Celery", CropTolerance.NEUTRAL);
        toleranceMap.put("Fennel", "Chard", CropTolerance.NEUTRAL);
        toleranceMap.put("Fennel", "ChineseCabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Fennel", "Cucumber", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Fennel", "Endive", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Fennel", "Fennel", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Fennel", "Garlic", CropTolerance.NEUTRAL);
        toleranceMap.put("Fennel", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Fennel", "Kohlrabi", CropTolerance.NEUTRAL);
        toleranceMap.put("Fennel", "LambsLettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Fennel", "Leek", CropTolerance.NEUTRAL);
        toleranceMap.put("Fennel", "Lettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Fennel", "Onion", CropTolerance.NEUTRAL);
        toleranceMap.put("Fennel", "Pea", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Fennel", "Potato", CropTolerance.NEUTRAL);
        toleranceMap.put("Fennel", "Radish", CropTolerance.NEUTRAL);
        toleranceMap.put("Fennel", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("Fennel", "RunnerBeans", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Fennel", "Spinach", CropTolerance.NEUTRAL);
        toleranceMap.put("Fennel", "Strawberry", CropTolerance.NEUTRAL);
        toleranceMap.put("Fennel", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("Garlic", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("Garlic", "Beetroot", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Garlic", "BushBean", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Garlic", "Cabbage", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Garlic", "Carrot", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Garlic", "Celery", CropTolerance.NEUTRAL);
        toleranceMap.put("Garlic", "Chard", CropTolerance.NEUTRAL);
        toleranceMap.put("Garlic", "ChineseCabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Garlic", "Cucumber", CropTolerance.NEUTRAL);
        toleranceMap.put("Garlic", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("Garlic", "Fennel", CropTolerance.NEUTRAL);
        toleranceMap.put("Garlic", "Garlic", CropTolerance.NEUTRAL);
        toleranceMap.put("Garlic", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Garlic", "Kohlrabi", CropTolerance.NEUTRAL);
        toleranceMap.put("Garlic", "LambsLettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Garlic", "Leek", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Garlic", "Lettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Garlic", "Onion", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Garlic", "Pea", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Garlic", "Potato", CropTolerance.NEUTRAL);
        toleranceMap.put("Garlic", "Radish", CropTolerance.NEUTRAL);
        toleranceMap.put("Garlic", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("Garlic", "RunnerBeans", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Garlic", "Spinach", CropTolerance.NEUTRAL);
        toleranceMap.put("Garlic", "Strawberry", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Garlic", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("Horseradish", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Beetroot", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "BushBean", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Cabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Carrot", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Celery", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Chard", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "ChineseCabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Cucumber", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Fennel", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Garlic", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Kohlrabi", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "LambsLettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Leek", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Lettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Onion", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Pea", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Potato", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Horseradish", "Radish", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "RunnerBeans", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Spinach", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Strawberry", CropTolerance.NEUTRAL);
        toleranceMap.put("Horseradish", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("Kohlrabi", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("Kohlrabi", "Beetroot", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Kohlrabi", "BushBean", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Kohlrabi", "Cabbage", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Kohlrabi", "Carrot", CropTolerance.NEUTRAL);
        toleranceMap.put("Kohlrabi", "Celery", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Kohlrabi", "Chard", CropTolerance.NEUTRAL);
        toleranceMap.put("Kohlrabi", "ChineseCabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Kohlrabi", "Cucumber", CropTolerance.NEUTRAL);
        toleranceMap.put("Kohlrabi", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("Kohlrabi", "Fennel", CropTolerance.NEUTRAL);
        toleranceMap.put("Kohlrabi", "Garlic", CropTolerance.NEUTRAL);
        toleranceMap.put("Kohlrabi", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Kohlrabi", "Kohlrabi", CropTolerance.NEUTRAL);
        toleranceMap.put("Kohlrabi", "LambsLettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Kohlrabi", "Leek", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Kohlrabi", "Lettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Kohlrabi", "Onion", CropTolerance.NEUTRAL);
        toleranceMap.put("Kohlrabi", "Pea", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Kohlrabi", "Potato", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Kohlrabi", "Radish", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Kohlrabi", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("Kohlrabi", "RunnerBeans", CropTolerance.NEUTRAL);
        toleranceMap.put("Kohlrabi", "Spinach", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Kohlrabi", "Strawberry", CropTolerance.NEUTRAL);
        toleranceMap.put("Kohlrabi", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("LambsLettuce", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("LambsLettuce", "Beetroot", CropTolerance.NEUTRAL);
        toleranceMap.put("LambsLettuce", "BushBean", CropTolerance.NEUTRAL);
        toleranceMap.put("LambsLettuce", "Cabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("LambsLettuce", "Carrot", CropTolerance.NEUTRAL);
        toleranceMap.put("LambsLettuce", "Celery", CropTolerance.NEUTRAL);
        toleranceMap.put("LambsLettuce", "Chard", CropTolerance.NEUTRAL);
        toleranceMap.put("LambsLettuce", "ChineseCabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("LambsLettuce", "Cucumber", CropTolerance.NEUTRAL);
        toleranceMap.put("LambsLettuce", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("LambsLettuce", "Fennel", CropTolerance.SUPPORTIVE);
        toleranceMap.put("LambsLettuce", "Garlic", CropTolerance.SUPPORTIVE);
        toleranceMap.put("LambsLettuce", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("LambsLettuce", "Kohlrabi", CropTolerance.NEUTRAL);
        toleranceMap.put("LambsLettuce", "LambsLettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("LambsLettuce", "Leek", CropTolerance.SUPPORTIVE);
        toleranceMap.put("LambsLettuce", "Lettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("LambsLettuce", "Onion", CropTolerance.SUPPORTIVE);
        toleranceMap.put("LambsLettuce", "Pea", CropTolerance.NEUTRAL);
        toleranceMap.put("LambsLettuce", "Potato", CropTolerance.NEUTRAL);
        toleranceMap.put("LambsLettuce", "Radish", CropTolerance.SUPPORTIVE);
        toleranceMap.put("LambsLettuce", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("LambsLettuce", "RunnerBeans", CropTolerance.NEUTRAL);
        toleranceMap.put("LambsLettuce", "Spinach", CropTolerance.SUPPORTIVE);
        toleranceMap.put("LambsLettuce", "Strawberry", CropTolerance.SUPPORTIVE);
        toleranceMap.put("LambsLettuce", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("Leek", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("Leek", "Beetroot", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Leek", "BushBean", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Leek", "Cabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Leek", "Carrot", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Leek", "Celery", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Leek", "Chard", CropTolerance.NEUTRAL);
        toleranceMap.put("Leek", "ChineseCabbage", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Leek", "Cucumber", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Leek", "Endive", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Leek", "Fennel", CropTolerance.NEUTRAL);
        toleranceMap.put("Leek", "Garlic", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Leek", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Leek", "Kohlrabi", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Leek", "LambsLettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Leek", "Leek", CropTolerance.NEUTRAL);
        toleranceMap.put("Leek", "Lettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Leek", "Onion", CropTolerance.NEUTRAL);
        toleranceMap.put("Leek", "Pea", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Leek", "Potato", CropTolerance.NEUTRAL);
        toleranceMap.put("Leek", "Radish", CropTolerance.NEUTRAL);
        toleranceMap.put("Leek", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("Leek", "RunnerBeans", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Leek", "Spinach", CropTolerance.NEUTRAL);
        toleranceMap.put("Leek", "Strawberry", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Leek", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("Lettuce", "Aubergine", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Lettuce", "Beetroot", CropTolerance.NEUTRAL);
        toleranceMap.put("Lettuce", "BushBean", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Lettuce", "Cabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Lettuce", "Carrot", CropTolerance.NEUTRAL);
        toleranceMap.put("Lettuce", "Celery", CropTolerance.NEUTRAL);
        toleranceMap.put("Lettuce", "Chard", CropTolerance.NEUTRAL);
        toleranceMap.put("Lettuce", "ChineseCabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Lettuce", "Cucumber", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Lettuce", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("Lettuce", "Fennel", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Lettuce", "Garlic", CropTolerance.NEUTRAL);
        toleranceMap.put("Lettuce", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Lettuce", "Kohlrabi", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Lettuce", "LambsLettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Lettuce", "Leek", CropTolerance.NEUTRAL);
        toleranceMap.put("Lettuce", "Lettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Lettuce", "Onion", CropTolerance.NEUTRAL);
        toleranceMap.put("Lettuce", "Pea", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Lettuce", "Potato", CropTolerance.NEUTRAL);
        toleranceMap.put("Lettuce", "Radish", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Lettuce", "Rhubarb", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Lettuce", "RunnerBeans", CropTolerance.NEUTRAL);
        toleranceMap.put("Lettuce", "Spinach", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Lettuce", "Strawberry", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Lettuce", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("Onion", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("Onion", "Beetroot", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Onion", "BushBean", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Onion", "Cabbage", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Onion", "Carrot", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Onion", "Celery", CropTolerance.NEUTRAL);
        toleranceMap.put("Onion", "Chard", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Onion", "ChineseCabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Onion", "Cucumber", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Onion", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("Onion", "Fennel", CropTolerance.NEUTRAL);
        toleranceMap.put("Onion", "Garlic", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Onion", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Onion", "Kohlrabi", CropTolerance.NEUTRAL);
        toleranceMap.put("Onion", "LambsLettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Onion", "Leek", CropTolerance.NEUTRAL);
        toleranceMap.put("Onion", "Lettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Onion", "Onion", CropTolerance.NEUTRAL);
        toleranceMap.put("Onion", "Pea", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Onion", "Potato", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Onion", "Radish", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Onion", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("Onion", "RunnerBeans", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Onion", "Spinach", CropTolerance.NEUTRAL);
        toleranceMap.put("Onion", "Strawberry", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Onion", "Zucchini", CropTolerance.SUPPORTIVE);

        toleranceMap.put("Pea", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("Pea", "Beetroot", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Pea", "BushBean", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Pea", "Cabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Pea", "Carrot", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Pea", "Celery", CropTolerance.NEUTRAL);
        toleranceMap.put("Pea", "Chard", CropTolerance.NEUTRAL);
        toleranceMap.put("Pea", "ChineseCabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Pea", "Cucumber", CropTolerance.NEUTRAL);
        toleranceMap.put("Pea", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("Pea", "Fennel", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Pea", "Garlic", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Pea", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Pea", "Kohlrabi", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Pea", "LambsLettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Pea", "Leek", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Pea", "Lettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Pea", "Onion", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Pea", "Pea", CropTolerance.NEUTRAL);
        toleranceMap.put("Pea", "Potato", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Pea", "Radish", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Pea", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("Pea", "RunnerBeans", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Pea", "Spinach", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Pea", "Strawberry", CropTolerance.NEUTRAL);
        toleranceMap.put("Pea", "Zucchini", CropTolerance.SUPPORTIVE);

        toleranceMap.put("Potato", "Aubergine", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Potato", "Beetroot", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Potato", "BushBean", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Potato", "Cabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Potato", "Carrot", CropTolerance.NEUTRAL);
        toleranceMap.put("Potato", "Celery", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Potato", "Chard", CropTolerance.NEUTRAL);
        toleranceMap.put("Potato", "ChineseCabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Potato", "Cucumber", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Potato", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("Potato", "Fennel", CropTolerance.NEUTRAL);
        toleranceMap.put("Potato", "Garlic", CropTolerance.NEUTRAL);
        toleranceMap.put("Potato", "Horseradish", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Potato", "Kohlrabi", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Potato", "LambsLettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Potato", "Leek", CropTolerance.NEUTRAL);
        toleranceMap.put("Potato", "Lettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Potato", "Onion", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Potato", "Pea", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Potato", "Potato", CropTolerance.NEUTRAL);
        toleranceMap.put("Potato", "Radish", CropTolerance.NEUTRAL);
        toleranceMap.put("Potato", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("Potato", "RunnerBeans", CropTolerance.NEUTRAL);
        toleranceMap.put("Potato", "Spinach", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Potato", "Strawberry", CropTolerance.NEUTRAL);
        toleranceMap.put("Potato", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("Radish", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("Radish", "Beetroot", CropTolerance.NEUTRAL);
        toleranceMap.put("Radish", "BushBean", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Radish", "Cabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Radish", "Carrot", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Radish", "Celery", CropTolerance.NEUTRAL);
        toleranceMap.put("Radish", "Chard", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Radish", "ChineseCabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Radish", "Cucumber", CropTolerance.NEUTRAL);
        toleranceMap.put("Radish", "Endive", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Radish", "Fennel", CropTolerance.NEUTRAL);
        toleranceMap.put("Radish", "Garlic", CropTolerance.NEUTRAL);
        toleranceMap.put("Radish", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Radish", "Kohlrabi", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Radish", "LambsLettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Radish", "Leek", CropTolerance.NEUTRAL);
        toleranceMap.put("Radish", "Lettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Radish", "Onion", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Radish", "Pea", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Radish", "Potato", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Radish", "Radish", CropTolerance.NEUTRAL);
        toleranceMap.put("Radish", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("Radish", "RunnerBeans", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Radish", "Spinach", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Radish", "Strawberry", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Radish", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("Rhubarb", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "Beetroot", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "BushBean", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Rhubarb", "Cabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Rhubarb", "Carrot", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "Celery", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "Chard", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "ChineseCabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "Cucumber", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "Fennel", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "Garlic", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "Kohlrabi", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "LambsLettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Rhubarb", "Leek", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "Lettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "Onion", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "Pea", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "Potato", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "Radish", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "RunnerBeans", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Rhubarb", "Spinach", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Rhubarb", "Strawberry", CropTolerance.NEUTRAL);
        toleranceMap.put("Rhubarb", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("RunnerBeans", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("RunnerBeans", "Beetroot", CropTolerance.NEUTRAL);
        toleranceMap.put("RunnerBeans", "BushBean", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("RunnerBeans", "Cabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("RunnerBeans", "Carrot", CropTolerance.NEUTRAL);
        toleranceMap.put("RunnerBeans", "Celery", CropTolerance.SUPPORTIVE);
        toleranceMap.put("RunnerBeans", "Chard", CropTolerance.NEUTRAL);
        toleranceMap.put("RunnerBeans", "ChineseCabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("RunnerBeans", "Cucumber", CropTolerance.SUPPORTIVE);
        toleranceMap.put("RunnerBeans", "Endive", CropTolerance.SUPPORTIVE);
        toleranceMap.put("RunnerBeans", "Fennel", CropTolerance.NEUTRAL);
        toleranceMap.put("RunnerBeans", "Garlic", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("RunnerBeans", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("RunnerBeans", "Kohlrabi", CropTolerance.SUPPORTIVE);
        toleranceMap.put("RunnerBeans", "LambsLettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("RunnerBeans", "Leek", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("RunnerBeans", "Lettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("RunnerBeans", "Onion", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("RunnerBeans", "Pea", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("RunnerBeans", "Potato", CropTolerance.NEUTRAL);
        toleranceMap.put("RunnerBeans", "Radish", CropTolerance.SUPPORTIVE);
        toleranceMap.put("RunnerBeans", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("RunnerBeans", "RunnerBeans", CropTolerance.NEUTRAL);
        toleranceMap.put("RunnerBeans", "Spinach", CropTolerance.SUPPORTIVE);
        toleranceMap.put("RunnerBeans", "Strawberry", CropTolerance.NEUTRAL);
        toleranceMap.put("RunnerBeans", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("Spinach", "Aubergine", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Spinach", "Beetroot", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Spinach", "BushBean", CropTolerance.NEUTRAL);
        toleranceMap.put("Spinach", "Cabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Spinach", "Carrot", CropTolerance.NEUTRAL);
        toleranceMap.put("Spinach", "Celery", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Spinach", "Chard", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Spinach", "ChineseCabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Spinach", "Cucumber", CropTolerance.NEUTRAL);
        toleranceMap.put("Spinach", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("Spinach", "Fennel", CropTolerance.NEUTRAL);
        toleranceMap.put("Spinach", "Garlic", CropTolerance.NEUTRAL);
        toleranceMap.put("Spinach", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Spinach", "Kohlrabi", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Spinach", "LambsLettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Spinach", "Leek", CropTolerance.NEUTRAL);
        toleranceMap.put("Spinach", "Lettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Spinach", "Onion", CropTolerance.NEUTRAL);
        toleranceMap.put("Spinach", "Pea", CropTolerance.NEUTRAL);
        toleranceMap.put("Spinach", "Potato", CropTolerance.NEUTRAL);
        toleranceMap.put("Spinach", "Radish", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Spinach", "Rhubarb", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Spinach", "RunnerBeans", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Spinach", "Spinach", CropTolerance.NEUTRAL);
        toleranceMap.put("Spinach", "Strawberry", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Spinach", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("Strawberry", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("Strawberry", "Beetroot", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Strawberry", "BushBean", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Strawberry", "Cabbage", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Strawberry", "Carrot", CropTolerance.NEUTRAL);
        toleranceMap.put("Strawberry", "Celery", CropTolerance.NEUTRAL);
        toleranceMap.put("Strawberry", "Chard", CropTolerance.NEUTRAL);
        toleranceMap.put("Strawberry", "ChineseCabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Strawberry", "Cucumber", CropTolerance.NEUTRAL);
        toleranceMap.put("Strawberry", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("Strawberry", "Fennel", CropTolerance.NEUTRAL);
        toleranceMap.put("Strawberry", "Garlic", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Strawberry", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Strawberry", "Kohlrabi", CropTolerance.NEUTRAL);
        toleranceMap.put("Strawberry", "LambsLettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Strawberry", "Leek", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Strawberry", "Lettuce", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Strawberry", "Onion", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Strawberry", "Pea", CropTolerance.NEUTRAL);
        toleranceMap.put("Strawberry", "Potato", CropTolerance.NEUTRAL);
        toleranceMap.put("Strawberry", "Radish", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Strawberry", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("Strawberry", "RunnerBeans", CropTolerance.NEUTRAL);
        toleranceMap.put("Strawberry", "Spinach", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Strawberry", "Strawberry", CropTolerance.NEUTRAL);
        toleranceMap.put("Strawberry", "Zucchini", CropTolerance.NEUTRAL);

        toleranceMap.put("Zucchini", "Aubergine", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "Beetroot", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Zucchini", "BushBean", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "Cabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "Carrot", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "Celery", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "Chard", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "ChineseCabbage", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "Cucumber", CropTolerance.OBSTRUCTIVE);
        toleranceMap.put("Zucchini", "Endive", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "Fennel", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "Garlic", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "Horseradish", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "Kohlrabi", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "LambsLettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "Leek", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "Lettuce", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "Onion", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Zucchini", "Pea", CropTolerance.SUPPORTIVE);
        toleranceMap.put("Zucchini", "Potato", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "Radish", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "Rhubarb", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "RunnerBeans", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "Spinach", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "Strawberry", CropTolerance.NEUTRAL);
        toleranceMap.put("Zucchini", "Zucchini", CropTolerance.NEUTRAL);
    }
}